package unicam.spm2023.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SeleniumIDETest1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seleniumIDETest1() {
    driver.get("https://pros.unicam.it/");
    driver.manage().window().setSize(new Dimension(1052, 803));
    driver.findElement(By.cssSelector(".post-id-2620 .ultp-block-image > a")).click();
    driver.findElement(By.cssSelector(".toggle-search")).click();
    driver.findElement(By.name("s")).sendKeys("bpmn");
    driver.findElement(By.name("s")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".type-portfolio:nth-child(3) .attachment-gridframe-medium-h")).click();
    driver.findElement(By.linkText("PROS")).click();
    driver.findElement(By.cssSelector(".amazingslider-arrow-left-1")).click();
    driver.findElement(By.cssSelector(".amazingslider-arrow-left-1")).click();
    driver.findElement(By.cssSelector(".amazingslider-play-1")).click();
    driver.switchTo().frame(1);
    driver.findElement(By.cssSelector(".video-stream")).click();
  }
}
